apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mongo.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "mongo.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "mongo.name" . }}
    spec:
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      containers:
        - name: mongodb
          image: "bitnami/mongodb"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MONGODB_USERNAME
              value: "my_user"
            - name: MONGODB_PASSWORD
              value: "password123"
            - name: MONGODB_DATABASE
              value: "employees"
            - name: ALLOW_EMPTY_PASSWORD
              value: "true"
          ports:
            - containerPort: {{ .Values.service.port }}
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: {{ include "mongo.fullname" . }}-pvc
