apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "mongo.fullname" . }}-pv
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - {{ .Values.persistence.accessModes }}
  hostPath:
    path: {{ .Values.persistence.hostPath }}
