apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "client.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "client.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "client.name" . }}
    spec:
      containers:
        - name: client
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: SERVER_URL
              value: "{{ .Values.env.SERVER_URL }}"
            - name: SERVER_PORT
              value: "{{ .Values.env.SERVER_PORT }}"
