apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "client.fullname" . }}-ingress
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.hosts }}
    secretName: {{ .Values.ingress.secretName }}
  rules:
  - host: {{ .Values.ingress.hosts }}
    http:
      paths:
      - path: {{ .Values.ingress.clientPath }}
        pathType: {{ .Values.ingress.clientPathType }}
        backend:
          service:
            name: {{ .Values.ingress.clientName }}
            port:
              number: {{ .Values.ingress.clientPort }}
      - path: {{ .Values.ingress.servicePath }}
        pathType: {{ .Values.ingress.servicePathType }}
        backend:
          service:
            name: {{ .Values.ingress.serviceName }}
            port: 
              number: {{ .Values.ingress.servicePort }}
