apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "client.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
