apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
spec:
  storageClassName: standard # Replace with your desired storage class
  capacity:
    storage: 1Gi # Adjust storage size as needed
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/mongodb

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
spec:
  storageClassName: standard # Match the PV's storage class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
spec:
  replicas: 1 # Adjust as needed
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: bitnami/mongodb:latest
          env:
            - name: MONGODB_USERNAME
              value: my_user
            - name: MONGODB_PASSWORD
              value: password123
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
            - name: MONGODB_DATABASE
              value: employees
          ports:
            - containerPort: 27017
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-pvc
