# Default values for MERN server.
replicaCount: 1

image:
  repository: server
  tag: latest
  pullPolicy: Never

service:
  type: NodePort
  port: 5000
  nodePort: 30001

livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  initialDelaySeconds: 10
  periodSeconds: 10

server:
  auth:
    password: "password123"
    username: "my_user"
    database: "employees"
    host: "mongodb"
    port: "27017"

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "200m"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 70