# Default values for MERN server.
replicaCount: 1

image:
  repository: server-5
  tag: latest
  pullPolicy: Never

service:
  type: NodePort
  port: 5000
  nodePort: 30001

livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  initialDelaySeconds: 10
  periodSeconds: 10

server:
  auth:
    password: "password123"
    username: "my_user"
    database: "employees"
