apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongo.fullname" . }}-secret
type: Opaque
data:
  mongodb-password: {{ .Values.mongodb.auth.password | b64enc }}
  mongodb-username: {{ .Values.mongodb.auth.username | b64enc }}
  mongodb-database: {{ .Values.mongodb.auth.database | b64enc }}
