apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: client
        ports:
        - containerPort: 3000
        imagePullPolicy: Never
        env:
        - name: SERVER_URL
          value: "http://192.168.49.2"
        - name: SERVER_PORT
          value: "30001"
