apiVersion: v1
kind: Service
metadata:
  name: mern-server-service
spec:
  type: NodePort
  selector:
    app: mern-server
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30001 # Optional: specify a node port; otherwise, a random port in the NodePort range is assigned
