# Default values for MERN client.
replicaCount: 1

image:
  repository: client
  pullPolicy: Never

service:
  type: ClusterIP
  port: 3000
  name: client-service

ingress:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/"
  hosts:
    paths:
    - path: "/"
      pathType: Prefix

livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 10



env:
  SERVER_URL: "http://192.168.49.2" # Change as needed
  SERVER_PORT: "30001"
