# Default values for MERN client.
replicaCount: 1

image:
  repository: client
  pullPolicy: Never

service:
  type: NodePort 
  port: 80        
  targetPort: 80  

ingress:
  hosts: mern.minikube.test
  secretName: mern-tls
  host: mern.minikube.test
  clientName: client
  clientPath: /
  clientPort: 80
  clientPathType: Prefix
  serviceName: server
  servicePath: /api
  servicePort: 5000
  servicePathType: Prefix




livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 10

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "200m"

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 1000
  targetMemoryUtilizationPercentage: 300