apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "server.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "server.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "server.name" . }}
    spec:
      containers:
        - name: mern-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
          - name: MONGODB_USERNAME
            valueFrom:
              secretKeyRef:
                name: server-secret
                key: username
          - name: MONGODB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: server-secret
                key: password
          - name: MONGODB_DATABASE
            valueFrom:
              secretKeyRef:
                name: server-secret
                key: database
          - name: MONGODB_HOST
            value: "mongodb" 
          - name: MONGODB_PORT
            value: "27017"
