apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "server.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "server.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "server.name" . }}
    spec:
      containers:
        - name: mern-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "server.fullname" . }}-secret
                  key: mongodb-username
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "server.fullname" . }}-secret
                  key: mongodb-password
            - name: MONGODB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ include "server.fullname" . }}-secret
                  key: mongodb-database
            - name: MONGODB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ include "server.fullname" . }}-secret
                  key: mongodb-host
            - name: MONGODB_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ include "server.fullname" . }}-secret
                  key: mongodb-port
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.port }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.port }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          resources:
            requests:
              memory: "{{ .Values.resources.requests.memory }}"
              cpu: "{{ .Values.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.resources.limits.memory }}"
              cpu: "{{ .Values.resources.limits.cpu }}"