apiVersion: v1
kind: Secret
metadata:
  name: {{ include "server.fullname" . }}-secret
type: Opaque
data:
  mongodb-password: {{ .Values.server.auth.password | b64enc }}
  mongodb-username: {{ .Values.server.auth.username | b64enc }}
  mongodb-database: {{ .Values.server.auth.database | b64enc }}
  mongodb-host: {{ .Values.server.auth.host | b64enc }}
  mongodb-port: {{ .Values.server.auth.port | b64enc }}



