apiVersion: v1
kind: Secret
metadata:
  name: {{ include "server.fullname" . }}-secret
type: Opaque
data:
  password: {{ .Values.server.auth.password | b64enc }}
  username: {{ .Values.server.auth.username | b64enc }}
  database: {{ .Values.server.auth.database | b64enc }}
